CREATE   PROCEDURE SP_BRIDGE_PARTY_NATIONALITY
AS
BEGIN
    SET NOCOUNT ON;

    -- Drop the table if it exists
    IF OBJECT_ID('[BRIDGE_PARTY_NATIONALITY_ACTIVE]', 'U') IS NOT NULL
        DROP TABLE [BRIDGE_PARTY_NATIONALITY_ACTIVE];

    -- Recreate the table
    CREATE TABLE [BRIDGE_PARTY_NATIONALITY_ACTIVE] (
        SK_BRIDGE_PARTY_NATIONALITY VARCHAR(36),
        SK_PARTY_NATIONALITY        VARCHAR(36),
        SK_PARTY_DETAIL             VARCHAR(36),
        START_DATE                  DATETIME,
        END_DATE                    DATETIME
    );

    -- Insert data
    INSERT INTO [BRIDGE_PARTY_NATIONALITY_ACTIVE]
    SELECT 
        CAST(SK_BRIDGE_PARTY_NATIONALITY AS VARCHAR(36)),
        CAST(SK_PARTY_NATIONALITY        AS VARCHAR(36)),
        CAST(SK_PARTY_DETAIL              AS VARCHAR(36)),
        START_DATE,
        END_DATE
    FROM [gold].[BRIDGE_PARTY_NATIONALITY]
    WHERE END_DATE IS NULL;
END;