CREATE   PROCEDURE SP_DEMOGRAPHICS_FACTLESS
AS
BEGIN
    SET NOCOUNT ON;

    -- Drop the table if it exists
    IF OBJECT_ID('[DEMOGRAPHICS_FACTLESS_ACTIVE]', 'U') IS NOT NULL
        DROP TABLE [DEMOGRAPHICS_FACTLESS_ACTIVE];

    -- Recreate the table
    CREATE TABLE [DEMOGRAPHICS_FACTLESS_ACTIVE] (
        SK_PARTY_DEMO_FACTLESS VARCHAR(36),
        SK_PARTY_DETAIL        VARCHAR(36),
        SK_PARTY_CONTACT       VARCHAR(36),
        SK_PARTY_FLAG          VARCHAR(36),
        SK_START_DATE          INT,
        SK_END_DATE            INT,
        START_DATE             DATE,
        END_DATE               DATE,
        LOAD_DATE              DATETIME
    );

    -- Insert data
    INSERT INTO [DEMOGRAPHICS_FACTLESS_ACTIVE]
    SELECT 
        CAST(F.SK_PARTY_DEMO_FACTLESS AS VARCHAR(36)),
        CAST(F.SK_PARTY_DETAIL        AS VARCHAR(36)),
        CAST(F.SK_PARTY_CONTACT       AS VARCHAR(36)),
        CAST(F.SK_PARTY_FLAG          AS VARCHAR(36)),
        F.SK_START_DATE,
        F.SK_END_DATE,
        TRY_CONVERT(DATE, CONVERT(VARCHAR(8), F.SK_START_DATE)),
        TRY_CONVERT(DATE, CONVERT(VARCHAR(8), F.SK_END_DATE)),
        F.LOAD_DATE
    FROM [gold].[PARTY_DEMOGRAPHICS_FACTLESS] F
    WHERE F.SK_END_DATE IS NULL;
END;