CREATE     PROCEDURE SP_PARTY_NATIONALITY
AS
BEGIN
    SET NOCOUNT ON;

    -- Drop the table if it exists
    IF OBJECT_ID('[PARTY_NATIONALITY_ACTIVE]', 'U') IS NOT NULL
        DROP TABLE [PARTY_NATIONALITY_ACTIVE];

    -- Recreate the table
    CREATE TABLE [PARTY_NATIONALITY_ACTIVE] (
        SK_PARTY_NATIONALITY   VARCHAR(36),
        PARTY_MDM_ID           VARCHAR(50),
        NATIONALITY            VARCHAR(100),
        FIRST_DECL_NTNLTY_FLAG BIT
    );

    -- Insert data
    INSERT INTO [PARTY_NATIONALITY_ACTIVE]
    SELECT 
        CAST(N.SK_PARTY_NATIONALITY AS VARCHAR(36)) AS SK_PARTY_NATIONALITY,
        D.PARTY_MDM_ID,
        CASE 
            WHEN N.NATIONALITY IS NULL THEN 'UNKNOWN'
            ELSE N.NATIONALITY
        END AS NATIONALITY,
        N.FIRST_DECL_NTNLTY_FLAG
    FROM [gold].[DIM_PARTY_DETAIL] D
    LEFT JOIN [gold].[DIM_PARTY_NATIONALITY] N
           ON N.PARTY_MDM_ID = D.PARTY_MDM_ID
          AND N.END_DATE IS NULL
    WHERE (D.RELATIONSHIP_END_DATE IS NULL
           OR D.RELATIONSHIP_END_DATE > GETDATE())
      AND D.END_DATE IS NULL;
END;