CREATE     PROCEDURE SP_PARTY_CONTACT
AS
BEGIN
    SET NOCOUNT ON;

    -- Drop the table if it exists
    IF OBJECT_ID('[PARTY_CONTACT_ACTIVE]', 'U') IS NOT NULL
        DROP TABLE [PARTY_CONTACT_ACTIVE];

    -- Recreate the table
    CREATE TABLE [PARTY_CONTACT_ACTIVE] (
        SK_PARTY_CONTACT VARCHAR(36),
        PARTY_MDM_ID     VARCHAR(50),
        POSTCODE         VARCHAR(20),
        COUNTRY          VARCHAR(50),
        ADDRESS_TYPE     VARCHAR(50)
    );

    -- Insert data
    INSERT INTO [PARTY_CONTACT_ACTIVE]
    SELECT 
        CAST(PC.SK_PARTY_CONTACT AS VARCHAR(36)) AS SK_PARTY_CONTACT,
        PD.PARTY_MDM_ID,
        PC.POSTCODE,
        PC.COUNTRY,
        PC.ADDRESS_TYPE
    FROM [gold].[DIM_PARTY_DETAIL] PD
    LEFT JOIN [gold].[DIM_PARTY_CONTACT] PC
        ON PC.PARTY_MDM_ID = PD.PARTY_MDM_ID
       AND PC.END_DATE IS NULL
    WHERE PD.END_DATE IS NULL
      AND (
            PD.RELATIONSHIP_END_DATE IS NULL
            OR PD.RELATIONSHIP_END_DATE > GETDATE()
          );
END;