CREATE    procedure  Test_Party_Details
AS



INSERT INTO [dbo].[DIM_PARTY_DETAIL]
           (
           [PARTY_MDM_ID]
           ,[PARTY_TYPE]
           ,[STATUS]
           ,[FIRST_NAMES]
           ,[LAST_NAME]
           ,[TITLE]
           ,[SUFFIX]
           ,[GENDER]
           ,[DOB]
           ,[MARITAL_STATUS]
           ,[NI_NUMBER]
           ,[TAX_ID_NUMBER]
           ,[TAX_DOMICILE]
           ,[FATCA_ELIGIBLE]
           ,[RELATIONSHIP_START_DATE]
           ,[RELATIONSHIP_END_DATE]
           ,[RETENTION_END_DATE]
           ,[DECEASED_DATE]
           ,[DECEASED_NOTIFICATION_DATE]
           ,[DECEASED_EVIDENCE_DATE]
           ,[START_DATE]
           ,[END_DATE]
           ,[HASH_VALUE]
           ,[DELETED_FLAG]
           ,[BATCH_ID])

SELECT 

PEOPLE.PARTY_ID	AS	PARTY_MDM_ID,
'' as [PARTY_TYPE],
'' as [STATUS],
PEOPLE.FIRST_NAMES AS FIRST_NAMES,
PEOPLE.LAST_NAME AS LAST_NAME,
'' AS TITLE,
PEOPLE.SUFFIX AS SUFFIX,
''  AS [GENDER],
PEOPLE.DATE_OF_BIRTH AS [DOB],
'' AS [MARITAL_STATUS],
PEOPLE.NATIONAL_INSURANCE_NUMBER NI_NUMBER,
PEOPLE.TAX_ID_NUMBER		TAX_ID_NUMBER,
PEOPLE.TAX_DOMICILE_CODE		TAX_DOMICILE,
'' as [FATCA_ELIGIBLE],
PEOPLE.RELATIONSHIP_START_DATE		RELATIONSHIP_START_DATE,
PEOPLE.RELATIONSHIP_END_DATE		RELATIONSHIP_END_DATE,
'' as [RETENTION_END_DATE],
PEOPLE.DECEASED_DATE		DECEASED_DATE,
PEOPLE.DECEASED_NOTIFICATION_DATE		DECEASED_NOTIFICATION_DATE,
PEOPLE.DECEASED_EVIDENCE_DATE		DECEASED_EVIDENCE_DATE,
PEOPLE.VALID_FROM		START_DATE,
PEOPLE.VALID_TO		END_DATE,
'' as HASH_VALUE,
'' as DELETED_FLAG,
'' as BATCH_ID
FROM 

[LHDEVGOLDSTAGINGTEMP].[silver].[people] people