-- Auto Generated (Do not modify) 755E13CE3799A96157641272389AC1067C7DCCFFC5EEB1E9CDDBC8B5D77F9052
CREATE             VIEW [gold].[VW_BRIDGE_PARTY_NATIONALITY]
AS SELECT 
 CAST( SK_BRIDGE_PARTY_NATIONALITY AS VARCHAR(36)) AS  [SK_BRIDGE_PARTY_NATIONALITY],
CAST( SK_PARTY_NATIONALITY AS VARCHAR(36)) AS	[SK_PARTY_NATIONALITY],
		CAST( SK_PARTY_DETAIL AS VARCHAR(36)) AS	[SK_PARTY_DETAIL],
			[START_DATE],
			[END_DATE]
FROM 
[gold].[BRIDGE_PARTY_NATIONALITY]
WHERE  END_DATE IS NULL;