-- Auto Generated (Do not modify) DCC608CA01AC71058D8B4C7C49D7BFDCB0463A67B2DF8ECF51AB6FEE44FA8A31
CREATE         VIEW [gold].[VW_DEMOGRAPHICS_FACTLESS]
AS  
SELECT CAST( SK_PARTY_DEMO_FACTLESS AS VARCHAR(36)) AS   SK_PARTY_DEMO_FACTLESS, 
CAST( SK_PARTY_DETAIL AS VARCHAR(36)) AS SK_PARTY_DETAIL, 
CAST( SK_PARTY_CONTACT AS VARCHAR(36)) AS SK_PARTY_CONTACT ,
CAST(SK_PARTY_FLAG AS VARCHAR(36)) AS SK_PARTY_FLAG, SK_START_DATE,SK_END_DATE,
TRY_CONVERT(DATE,CONVERT(VARCHAR(8),SK_START_DATE)) AS START_DATE,
TRY_CONVERT(DATE, CONVERT(VARCHAR(8), SK_END_DATE)) AS END_DATE,
LOAD_DATE

FROM [gold].[PARTY_DEMOGRAPHICS_FACTLESS]