-- Auto Generated (Do not modify) BAD866CFF6A0AA82E021957FE841FC3C459901079D90AA65D10B6BA3C81F14AC
CREATE             VIEW [gold].[VW_DIM_DATE]
AS 
SELECT 

[SK_DATE],
			[CALENDAR_DATE],
			[MONTH_NUMBER_IN_YEAR],
			
			[YEAR_NUMBER],

			[MONTH_NAME],
			
			[FISCAL_YEAR],
			
			[LOAD_DATE],
			[LOAD_TIME]

FROM [gold].[DIM_DATE] D
WHERE D.CALENDAR_DATE BETWEEN

--  MIN DATE
(
    SELECT
        CASE
            WHEN F.MIN_START_DATE IS NOT NULL AND P.MIN_REL_DATE IS NOT NULL THEN
                CASE 
                    WHEN F.MIN_START_DATE < P.MIN_REL_DATE THEN F.MIN_START_DATE
                    ELSE P.MIN_REL_DATE
                END
            WHEN F.MIN_START_DATE IS NOT NULL THEN F.MIN_START_DATE
            ELSE P.MIN_REL_DATE
        END
    FROM
        (SELECT MIN(CONVERT(date, CONVERT(varchar(8), SK_START_DATE))) AS MIN_START_DATE 
         FROM [gold].[PARTY_DEMOGRAPHICS_FACTLESS]
         WHERE SK_START_DATE IS NOT NULL) F
    CROSS JOIN
        (SELECT MIN(RELATIONSHIP_START_DATE) AS MIN_REL_DATE 
         FROM [gold].[DIM_PARTY_DETAIL] 
         WHERE RELATIONSHIP_START_DATE IS NOT NULL) P
)

AND

--  MAX DATE
(
    SELECT
        CASE
            WHEN F.MAX_START_DATE IS NOT NULL AND P.MAX_REL_DATE IS NOT NULL THEN
                CASE 
                    WHEN F.MAX_START_DATE > P.MAX_REL_DATE THEN F.MAX_START_DATE
                    ELSE P.MAX_REL_DATE
                END
            WHEN F.MAX_START_DATE IS NOT NULL THEN F.MAX_START_DATE
            ELSE P.MAX_REL_DATE
        END
    FROM
        (SELECT MAX(CONVERT(date, CONVERT(varchar(8),SK_START_DATE))) AS MAX_START_DATE 
         FROM [gold].[PARTY_DEMOGRAPHICS_FACTLESS] 
         WHERE SK_START_DATE IS NOT NULL) F
    CROSS JOIN
        (SELECT MAX(RELATIONSHIP_START_DATE) AS MAX_REL_DATE 
         FROM [gold].[DIM_PARTY_DETAIL]
         WHERE RELATIONSHIP_START_DATE IS NOT NULL) P
);