-- Auto Generated (Do not modify) E91EE57DC935B878DED7C73ADD496824D99FCC515ECF8551418331BEC1AFB02F
CREATE                   VIEW [gold].[VW_PARTY_NATIONALITY]


AS
SELECT CAST( N.SK_PARTY_NATIONALITY AS VARCHAR(36)) AS [SK_PARTY_NATIONALITY],
D.[PARTY_MDM_ID], CASE WHEN N.[NATIONALITY] IS NULL THEN 'UNKNOWN' else N.[NATIONALITY] END as NATIONALITY,
N.[FIRST_DECL_NTNLTY_FLAG]
FROM
[gold].[DIM_PARTY_DETAIL] D
LEFT JOIN [gold].[DIM_PARTY_NATIONALITY] N ON N.PARTY_MDM_ID = D.PARTY_MDM_ID
AND N.END_DATE IS NULL
WHERE (D.RELATIONSHIP_END_DATE IS NULL OR D.RELATIONSHIP_END_DATE > GETDATE() ) AND D.END_DATE IS NULL