-- Auto Generated (Do not modify) EE3295A7921AACC2826F51FA40D8FB7ACE7CFA9F8757BD16884B16AEAFC8E1E2
CREATE             VIEW [gold].[VW_PARTY_DETAIL]
AS SELECT CAST( SK_PARTY_DETAIL AS VARCHAR(36)) AS SK_PARTY_DETAIL, PARTY_MDM_ID, GENDER, PARTY_TYPE,DOB,[RELATIONSHIP_START_DATE],
FORMAT(RELATIONSHIP_START_DATE,'yyyy') AS RELATIONSHIP_START_YEAR,
DATEDIFF(YEAR, RELATIONSHIP_START_DATE, GETDATE()) AS CUSTOMER_TENURE_YEARS,
CASE
	WHEN RELATIONSHIP_START_DATE IS NULL
	THEN 'Unknown'
 	WHEN DATEDIFF(YEAR, RELATIONSHIP_START_DATE, GETDATE()) < 5
	THEN '0-5 Years'
	WHEN DATEDIFF(YEAR, RELATIONSHIP_START_DATE, GETDATE()) < 10
	THEN '5-10 Years'
	WHEN DATEDIFF(YEAR, RELATIONSHIP_START_DATE, GETDATE()) < 20
	THEN '10-20 Years'
	ELSE '20+ Years'
	END AS CUSTOMER_TENURE_BAND,

		[START_DATE],
		[END_DATE]
FROM [gold].[DIM_PARTY_DETAIL] WHERE RELATIONSHIP_END_DATE IS NULL OR RELATIONSHIP_END_DATE > GETDATE()