-- Auto Generated (Do not modify) C2C7DC2B5A18F199A4BEA2749A22BD0A9F79BECB9EC403390C60C7BC64D93B63
CREATE               VIEW [gold].[VW_PARTY_FLAG]
AS SELECT CAST( SK_PARTY_FLAG AS VARCHAR(36)) AS [SK_PARTY_FLAG],
			[PARTY_MDM_ID],
			[IS_ASSUMED_VC_FLAG],
			[IS_DORMANT_FLAG],
			[IS_DECEASED_FLAG],
			[MCNR_DEBT_FLAG],
			[OPEN_COMPLAINT_FLAG],
			[OPEN_LITIGATION_FLAG]
FROM [gold].[DIM_PARTY_FLAG]
WHERE END_DATE IS NULL;