-- Auto Generated (Do not modify) 31919D74BACE94B6B4FA3840BD33A8CB74AEA6053BE35FD2658958E7D69372BD
CREATE                     VIEW [gold].[VW_PARTY_CONTACT]
AS SELECT CAST( SK_PARTY_CONTACT AS VARCHAR(36)) AS [SK_PARTY_CONTACT],
            PD.[PARTY_MDM_ID],
            PC.[POSTCODE],
            PC.[COUNTRY],
       /*   CASE  
		  	WHEN PC.LINE_3 IS NULL OR LTRIM(RTRIM(PC.LINE_3))= '' THEN 'Unknown' ELSE 
			 PC.LINE_3  END AS REGION,*/
            PC.[ADDRESS_TYPE]
FROM [gold].[DIM_PARTY_DETAIL] PD
LEFT JOIN [gold].[DIM_PARTY_CONTACT] PC ON PC.PARTY_MDM_ID = PD.PARTY_MDM_ID 
AND PC.END_DATE IS NULL
WHERE  PD.END_DATE IS NULL
AND (PD.RELATIONSHIP_END_DATE IS NULL OR PD.RELATIONSHIP_END_DATE > GETDATE() )