CREATE TABLE [gold].[BRIDGE_PARTY_NATIONALITY] (

	[SK_BRIDGE_PARTY_NATIONALITY] uniqueidentifier NOT NULL, 
	[SK_PARTY_NATIONALITY] uniqueidentifier NOT NULL, 
	[SK_PARTY_DETAIL] uniqueidentifier NOT NULL, 
	[START_DATE] datetime2(3) NOT NULL, 
	[END_DATE] datetime2(3) NULL, 
	[HASH_VALUE] varchar(256) NULL, 
	[DELETED_FLAG] varchar(1) NULL, 
	[BATCH_ID] varchar(256) NOT NULL
);


GO
ALTER TABLE [gold].[BRIDGE_PARTY_NATIONALITY] ADD CONSTRAINT BPARNT_PK primary key NONCLUSTERED ([SK_BRIDGE_PARTY_NATIONALITY]);
GO
ALTER TABLE [gold].[BRIDGE_PARTY_NATIONALITY] ADD CONSTRAINT BPARNT_DPARDT_FK FOREIGN KEY ([SK_PARTY_DETAIL]) REFERENCES [gold].[DIM_PARTY_DETAIL]([SK_PARTY_DETAIL]);
GO
ALTER TABLE [gold].[BRIDGE_PARTY_NATIONALITY] ADD CONSTRAINT BPARNT_DPARNT_FK FOREIGN KEY ([SK_PARTY_NATIONALITY]) REFERENCES [gold].[DIM_PARTY_NATIONALITY]([SK_PARTY_NATIONALITY]);