CREATE TABLE [gold].[PARTY_DEMOGRAPHICS_FACTLESS] (

	[SK_PARTY_DEMO_FACTLESS] uniqueidentifier NOT NULL, 
	[SK_PARTY_DETAIL] uniqueidentifier NOT NULL, 
	[SK_PARTY_CONTACT] uniqueidentifier NOT NULL, 
	[SK_PARTY_FLAG] uniqueidentifier NOT NULL, 
	[SK_START_DATE] bigint NULL, 
	[SK_END_DATE] bigint NULL, 
	[LOAD_DATE] date NULL, 
	[LOAD_TIME] datetime2(6) NULL, 
	[HASH_VALUE] varchar(256) NULL, 
	[DELETED_FLAG] varchar(1) NULL, 
	[BATCH_ID] varchar(256) NOT NULL
);


GO
ALTER TABLE [gold].[PARTY_DEMOGRAPHICS_FACTLESS] ADD CONSTRAINT PARDEM_PK primary key NONCLUSTERED ([SK_PARTY_DEMO_FACTLESS]);
GO
ALTER TABLE [gold].[PARTY_DEMOGRAPHICS_FACTLESS] ADD CONSTRAINT PARDEM_DDATE_FK1 FOREIGN KEY ([SK_START_DATE]) REFERENCES [gold].[DIM_DATE]([SK_DATE]);
GO
ALTER TABLE [gold].[PARTY_DEMOGRAPHICS_FACTLESS] ADD CONSTRAINT PARDEM_DDATE_FK2 FOREIGN KEY ([SK_END_DATE]) REFERENCES [gold].[DIM_DATE]([SK_DATE]);
GO
ALTER TABLE [gold].[PARTY_DEMOGRAPHICS_FACTLESS] ADD CONSTRAINT PARDEM_DPARCT_FK FOREIGN KEY ([SK_PARTY_CONTACT]) REFERENCES [gold].[DIM_PARTY_CONTACT]([SK_PARTY_CONTACT]);
GO
ALTER TABLE [gold].[PARTY_DEMOGRAPHICS_FACTLESS] ADD CONSTRAINT PARDEM_DPARDT_FK FOREIGN KEY ([SK_PARTY_DETAIL]) REFERENCES [gold].[DIM_PARTY_DETAIL]([SK_PARTY_DETAIL]);